### ISSUE TITLE
how to run this?

### ISSUE THREAD

**Issue by kabus202** [twilson63/express-couchUser#47]
Hi,

I installed this package from node. Package installed successful. But how can i run it?

when i run:

node ./node_modules/express-user-couchdb/init http://localhost:5984/_users

im getting the following error:

```
{ Error: Document update conflict.
    at Request._callback (/home/kabus/node_modules/nano/nano.js:319:39)
    at Request.self.callback (/home/kabus/node_modules/nano/node_modules/request/request.js:122:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/home/kabus/node_modules/nano/node_modules/request/request.js:888:14)
    at emitOne (events.js:101:20)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/home/kabus/node_modules/nano/node_modules/request/request.js:839:12)
    at emitNone (events.js:91:20)
  name: 'Error',
  scope: 'couch',
  status_code: 409,
  'status-code': 409,
```

How can i set the user credentials?

**Comment by DarkSnow** [comment]
I know this is a really old comment but I hit this same issue.

You can include the username and password for basic auth in the url itself, so http://user:password@localhost:5984/_users
